version: '3.8'

services:
  app:
    container_name: amihan_app
    image: next_js_image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
